log: info
ethereum:
  endpoint: "NETWORK ENDPOINT"
  gas_limit: 20000000
  gas_price: 10000000000
  private_key: "PRIVATE KEY"
validator_power: 100
initial_validators:
  - "ODIN VALIDATOR ADDRESS"
bridge_address_storage: "ADDRESS_STORAGE.txt"
